# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postattachment',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='fileType',
            field=models.CharField(default='.png', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.TextField(default='/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PostAttachment',
        ),
    ]
