# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170930_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fileName',
            field=models.CharField(default='poop', max_length=255),
            preserve_default=False,
        ),
    ]
